version: '3.9'

services:
  fastapi:
    build: .
    ports:
      - "17787:17787"
    container_name: fastapi_app
    command: >
      sh -c "python3 -c 'from main import create_db_and_tables; create_db_and_tables()' &&
             uvicorn main:app --host 0.0.0.0 --port 17787"
    volumes:
      - .:/app
    restart: always
